workflows:
  android-workflow:
    name: Android Debug APK Build
    max_build_duration: 60
    instance_type: linux
    environment:
      java: 17
      groups:
        - google_play # Optional: only if you add secrets later
    triggering:
      events:
        - push
      branches:
        - master
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android Debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - mdsalmanhelp0@gmail.com
          
